version: '3.8'

services:
  functious:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TOKEN=${TOKEN}
      - MONGODB=${MONGODB}
      - SENTRY_DSN=${SENTRY_DSN}
      - BOTID=${BOTID}
      - CDN=${CDN}
      - CDN_KEY=${CDN_KEY}
      - API_PORT=8889
      - API_KEY=${API_KEY}
      - WEBSITE_URL=${WEBSITE_URL}
      - FLUXER_REDIRECT_URI=${FLUXER_REDIRECT_URI}
      - FLUXER_CLIENT_SECRET=${FLUXER_CLIENT_SECRET}
      - FLUXER_CLIENT_ID=${FLUXER_CLIENT_ID}
    ports:
      - "8889:8889"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.functious.rule=Host(`functious.calaway.online`)"
      - "traefik.http.routers.functious.entrypoints=websecure"
      - "traefik.http.routers.functious.tls.certresolver=letsencrypt"
      - "traefik.http.services.functious.loadbalancer.server.port=8889"
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true